### PR TITLE
Update Cloudsmith Repository Resource Documentation

### PR DESCRIPTION
**Pull request by RoseSecurity**
# What and Why

- Updates documentation by linting the markdown and adding valid values to the argument references

### CODE REVIEW

**Comment by RoseSecurity** [comment]
@BartoszBlizniak This PR would provide explicit guidance on the available choices for the repository resource. Have you considered implementing `tfplugindocs` to automate the generation of provider documentation?

**Comment by BartoszBlizniak** [comment]
Hey @RoseSecurity + @noelgass thank you for your contributions! 

@RoseSecurity - unfortunately our tests are set up in a way that we won't be able to run them from a fork atm. I'm not sure if you have permissions to create a branch directly from this project, however, I'm more than happy to do this on your behalf now. 

I will also be taking a look at the suggested plugin doc, looks like something we could certainly utilise!

**Comment by BartoszBlizniak** [comment]
I've created a new PR for this so we can merge the changes there: https://github.com/cloudsmith-io/terraform-provider-cloudsmith/pull/88

Thank you for your contribution!

**Comment by RoseSecurity** [comment]
@BartoszBlizniak Thank you for merging this! If there is any way that I can support the team or assist in adding functionality to the provider, just say the word. I am actively developing modules and components that utilize this provider so I may have more potential PRs in the near future.

**Pull request closed without merging**
